from(bucket: "<bucket>")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "em")
  |> filter(fn: (r) => r["source"] == "csv")
  |> filter(fn: (r) => r["_field"] == "total_act_energy")
  |> filter(fn: (r) => r["device"] == "unten" or r["device"] == "oben")
  |> filter(fn: (r) => r["phase"] == "c" or r["phase"] == "b" or r["phase"] == "a")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
