name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: poetry
        
    - name: Install dependencies
      run: cd importer && poetry install

    - name: Create dummy config
      run: cp importer/example-config.py importer/config.py

    - name: Run checks
      run: cd importer && poetry run nox -s check
    - name: Test with pytest
      run: cd importer && poetry run pytest -m "not shelly"
